### PR TITLE
Fix issue 189

### LINKED ISSUE #189: purgo build fail at linux
I try to build an app using purego on ubuntu but it fails on linux
```bash
2024-01-07T05:12:29.4981059Z # github.com/cyberhan123/stable-diffusion-desktop
2024-01-07T05:12:29.4983718Z dlopen: unhandled relocation for purego_dlopen (type 46 (SDYNIMPORT) rtype 7 (R_CALL))
2024-01-07T05:12:29.4989379Z dlsym: unhandled relocation for purego_dlsym (type 46 (SDYNIMPORT) rtype 7 (R_CALL))
2024-01-07T05:12:29.4991109Z dlerror: unhandled relocation for purego_dlerror (type 46 (SDYNIMPORT) rtype 7 (R_CALL))
2024-01-07T05:12:29.4992706Z dlclose: unhandled relocation for purego_dlclose (type 46 (SDYNIMPORT) rtype 7 (R_CALL))
2024-01-07T05:12:29.5058987Z   [90m[90m•[0m[0m [39m[39mCompiling application: [0m[0m[30;101m[30;101m  ERROR  [0m[0m [91m[91mexit status 1[0m[0m
```
The following is the complete github action log:

[App, linuxamd64, ubuntu-latest.txt](https://github.com/ebitengine/purego/files/13852471/0_build.App.linuxamd64.ubuntu-latest.txt)

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
Use the standard Cgo import mechanism when CGO_ENABLED=1. This fixes an issue where sometimes the external linker would fail to add the dlfcn symbols causing a linker error.

Closes #189

### CODE REVIEW

File: cgo.go [hunk 1]
```diff
@@ -13,3 +13,4 @@ package purego
 // usually isn't possible to call into C without using that import. However, with purego
 // it is since we don't use `import "C"`!
 import _ "runtime/cgo"
+import _ "github.com/ebitengine/purego/internal/cgo"
```
Comment (hajimehoshi) [inline cgo.go:16]:
```go
import (
    _ "runtime/cgo"

    _ "github.com/ebitengine/purego/internal/cgo"
)
```

**Review by hajimehoshi — APPROVED** [review]
LGTM % comments

Should we cherry-pick this to 0.5?

**Review by hajimehoshi — APPROVED** [review]
Oh, can we have a test for this by the way?

**Review by hajimehoshi — CHANGES_REQUESTED** [review]
(Set the state to 'request changes' just in case)

File: internal/cgo/dlfcn_cgo_unix.go [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+package cgo
+
+/*
+ #cgo LDFLAGS: -ldl
+
+#include <dlfcn.h>
+*/
+import "C"
+import _ "unsafe" // for go:linkname
```
Comment (hajimehoshi) [inline internal/cgo/dlfcn_cgo_unix.go:14]: Add a space line

```go
import "C"

import _ "unsafe" // for go:linkname
```

**Comment by TotallyGamerJet** [comment]
I added a `buildtest` file. The GitHub workflow runs `go build -v ./...` which before this PR failed but with this PR works.

File: buildtest/main.go [hunk 3]
```diff
@@ -0,0 +1,17 @@
+// SPDX-License-Identifier: Apache-2.0
```
Comment (hajimehoshi) [inline buildtest/main.go:1]: `internal/buildtest` would be better, as this doesn't have to be a public API to users.

File: buildtest/main.go [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+
+import (
+	_ "github.com/ebitengine/purego"
+)
+
+import "C"
+
+// This file tests that build Cgo and purego at the same time succeeds to build (#189).
+func main() {
+
```
Comment (hajimehoshi) [inline buildtest/main.go:16]: Remove this empty line

**Review by hajimehoshi — COMMENTED** [review]
Thanks!

**Comment by hajimehoshi** [comment]
> Should we cherry-pick this to 0.5?

What do you think? (I think yes)

File: buildtest/main.go (hunk 3 above)
Comment (hajimehoshi) [reply buildtest/main.go:1]: Now the other test files are in direct children packages. These are NOT a Go package, but these also should be in internal packages IMO. Let's move buildtest into internal, and consider moving them later.

**Comment by TotallyGamerJet** [comment]
> > Should we cherry-pick this to 0.5?
> 
> What do you think? (I think yes)

As long as there are no merge conflicts I think so too.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!
