### PR TITLE
purego: fix float returns

### LINKED ISSUE #176: Float return Values dont work
This one always returns zero:
```golang
var getFrameTime func() float32
purego.RegisterLibFunc(&getFrameTime, raylibDll, "GetFrameTime")
delta := getFrameTime()
// delta is 0
```

When using the syscall package like this, it works:
```golang
getFrameTime, _ := syscall.GetProcAddress(handle, "GetFrameTime")
_, ret, _ := syscall.SyscallN(getFrameTime)
delta := *(*float32)(unsafe.Pointer(&ret))
// delta is 0.0166667
```

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
Float32 was being converted into float64 which isn't right.

Closes #176

### CODE REVIEW

**Comment by JupiterRider** [comment]
@TotallyGamerJet I tested this fix. It seems to work 🎉

**Comment by TotallyGamerJet** [comment]
Great! Just got to find a libc function that returns `float` so that there's test.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

Should we backport this to stable branches?

**Comment by TotallyGamerJet** [comment]
Yeah we can back port it since the fix is 5 lines.

**Comment by hajimehoshi** [comment]
Oh the tests are failing now?

File: func_test.go [hunk 1]
```diff
@@ -86,3 +87,38 @@ func Test_qsort(t *testing.T) {
 		}
 	}
 }
+
+func TestRegisterFunc_Floats(t *testing.T) {
+	library, err := getSystemLibrary()
+	if err != nil {
+		t.Errorf("couldn't get system library: %s", err)
```
Comment (hajimehoshi) [inline func_test.go:93]: t.Fatalf

File: func_test.go [hunk 2]
```diff
@@ -86,3 +87,38 @@ func Test_qsort(t *testing.T) {
...
+	}
+	libc, err := openLibrary(library)
+	if err != nil {
+		t.Errorf("failed to dlopen: %s", err)
```
Comment (hajimehoshi) [inline func_test.go:97]: t.Fatalf

**Comment by TotallyGamerJet** [comment]
Only because libc.so.6 on Ubuntu doesn't have a `sin` and `sinf` function for some reason. I changed the test to use `strtof` and `strtod` which I believe Ubuntu does have.

File: func_test.go (hunk 1 above)
Comment (TotallyGamerJet) [reply func_test.go:93]: Don't we want to run both functions before failing? t.Fatalf ends the test so we don't know if the other one succeeded or not.

Comment (hajimehoshi) [reply func_test.go:93]: When a system library is not found, we cannot test the other tests, right?

Comment (hajimehoshi) [reply func_test.go:93]: Or, is it possible that a library is found and an error is returned at the same time...?

Comment (TotallyGamerJet) [reply func_test.go:93]: That is true bc it will panic if the symbol isn't found. However, if the symbol is found it may not return the correct value which is what is being tested. We'd want to test both float32 and float64 even if one fails.

Comment (hajimehoshi) [reply func_test.go:93]: Does `getSystemLibrary` search symbols? I don't suggest replacing all `Errorf` with `Fatalf`. Rather, I suggest replacing only two `Errorf` for `getSystemLibrary` and `openLibrary`.

Comment (TotallyGamerJet) [reply func_test.go:93]: Oh ok. That makes sense. Should we do that then for `Test_qsort` too?

Comment (hajimehoshi) [reply func_test.go:93]: Yeah. (Also TestRegisterFunc?)

**Review by hajimehoshi — APPROVED** [review]
Still LGTM, thanks!

Please merge this with comments when you like. I'll cherry-pick the fix to 0.5 later (maybe tomorrow). Thank you for your quick work!

**Comment by hajimehoshi** [comment]
Didn't the tests pass yet?

**Comment by JupiterRider** [comment]
@TotallyGamerJet Could you tag this or something, so the code is available at pkg.go.dev?

**Comment by TotallyGamerJet** [comment]
I believe @hajimehoshi will do that

**Comment by hajimehoshi** [comment]
I'll add a tag few days after the last fix, not now.

**Comment by hajimehoshi** [comment]
> Please merge this with comments when you like.

My words were not good, but please wait for test results before merging, thanks!

**Comment by TotallyGamerJet** [comment]
Whoops sorry about that

**Comment by TotallyGamerJet** [comment]
@hajimehoshi  which did that commit fail in the 0.5 branch on Ubuntu? It passed in https://github.com/ebitengine/purego/pull/177/commits/877753f1a0d3782d7f5e281ed81fec0d0985d9fc

**Comment by hajimehoshi** [comment]
I cherry-picked 63c6fec935c5d014be719ef339e930658eb39213

**Comment by TotallyGamerJet** [comment]
I understand that. I was wondering why it had failed. It seems to be because 0.5 doesn't have #163 which added callbacks on Linux which the float tests need.

**Comment by hajimehoshi** [comment]
Thanks! We should not cherry-pick 092d3a90dd8b57e94832c070f4e2d4c79e410605 for 0.5 tests since this is risky. 

Then, I'd cherry-pick the fix with this code snippet to avoid tests on Linux as other tests do:

```go
        if runtime.GOOS == "linux" {                                                                                                                                                                                                                                                  
                // TODO: enable once callbacks are working properly on Linux                                                                                                                                                                                                          
                t.Skip("callbacks are not supported on Linux")                                                                                                                                                                                                                        
        } 
```

What do you think?

**Comment by hajimehoshi** [comment]
> What do you think?

I think we have reached an agreement :) https://github.com/ebitengine/purego/issues/176#issuecomment-1817585671

**Comment by TotallyGamerJet** [comment]
Yes. Your solution is a good one and the test passed on Linux
