### PR TITLE
dlfcn: rework error check

### LINKED ISSUE #118: Support for static initialization dlopen/dlsym calls
Hello,

I noticed that in [`dlopen`](https://github.com/ebitengine/purego/blob/main/dlfcn.go#L37) and [`dlsym`](https://github.com/ebitengine/purego/blob/ebd8567e49db0b4514b146f222a59dd1acd618b7/dlfcn.go#L49) in `dlfcn.go` , the return value is never checked against nil. Is there a reason for this ? This blocks the use of any call to dlopen or any similar function in the static initialization of the library loaded. In the end, if the inner call fails, the dlerror value set by the inner call would make the top call fail.

Do tell me if you need more precisions or if you want me to do a PR or an MRE.

### PR DESCRIPTION
**Pull request by eliottness**
This PR implements the fix described [here](https://github.com/ebitengine/purego/issues/118#issuecomment-1489992006)

The test added needs the testing environment to possess a C++ compiler, feel free to tell me if you have another idea to reproduce this behaviour without this new dependency.

Closes #118

### CODE REVIEW

File: dlfcn_test.go [hunk 1]
```diff
@@ -90,3 +94,33 @@ func Test_qsort(t *testing.T) {
 		}
 	}
 }
+
+
```
Comment (hajimehoshi) [inline dlfcn_test.go:98]: One empty line is ifne (Probably you need gofmt)

Comment (eliottness) [reply dlfcn_test.go]: Applied, thanks.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

I'd like to wait for @TotallyGamerJet's review
