### PR TITLE
Clarify Example section and Dl* windows equivalents

### LINKED ISSUE #273: Generic APIs are needed for multiple platforms (or documentation of differences with examples)
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] Android
- [X] iOS

### What feature would you like to be added?

I am in agreement with the points made by both @RomainMuller and @platypusguy in PR https://github.com/ebitengine/purego/pull/192. APIs should not burden the user with O/S specifics wherever possible. The precise API names are not so important as long as they are universal.

However, at least, the project documentation needs an update.

Reference: https://pkg.go.dev/github.com/ebitengine/purego

"Supported Platforms" states that the APIs are supported on the listed platforms with the exception of a ARM32 and Windows-32 environments. However, the "Example" states that the APIs only work on POSIX systems contradicts the previous documentation sections.

It would be helpful if an equivalent documentation example for Windows was provided.  Also, under each API where Windows is not currently supported (E.g. Dlopen), depict the equivalent operation for Windows. Then, users authoring multiplatform projects would have some guidance without having to engage in significant trial-and-error activity.

### Why is this needed?

My goal is to be able to open and use a Java library Windows, Linux, Unix, and MacOS on 64-bit hardware platforms. I'll take care with providing the full paths. The dlfcn concept & code of @RomainMuller will be useful to me in modifying my own work.

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
# What issue is this addressing?
Closes #273

## What _type_ of issue is this addressing?
n/a

## What this PR does | solves
Clarification on example code for windows in README and adding equivalent windows functions to

### CODE REVIEW

File: dlfcn.go [hunk 1]
```diff
@@ -33,6 +33,9 @@ func init() {
 // A second call to Dlopen with the same path will return the same handle, but the internal
 // reference count for the handle will be incremented. Therefore, all
 // Dlopen calls should be balanced with a Dlclose call.
+//
+// This function is not available on Windows.
+// Use [golang.org/x/sys/windows.LoadLibrary] behind a //go:build windows build tag.
```
Comment (hajimehoshi) [inline dlfcn.go:38]: Maybe,

```
Use [golang.org/x/sys/windows.LoadLibrary] for Windows instead.
```

? It's because `//go:build` is not needed if the file has `_windows` suffix.

Comment (hajimehoshi) [reply dlfcn.go:38]: Also, `NewLazyDLL` and `NewLazySystemDLL` are other options.

Comment (TotallyGamerJet) [reply dlfcn.go:38]: Should I list all three options?

Comment (hajimehoshi) [reply dlfcn.go:38]: I think so. (Offtopic: Personally `NewLazySystemDLL` is the best option, but the comment doesn't have to say this is the best)

**Comment by TotallyGamerJet** [comment]
Also, purego.Dlerror type is not available on Windows. I'm thinking I should add a comment to that too but there is no equivalent to it

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Comment by hajimehoshi** [comment]
> Also, purego.Dlerror type is not available on Windows. I'm thinking I should add a comment to that too but there is no equivalent to it

A comment about the fact there is not couterpart would be fine.

**Review by hajimehoshi — APPROVED** [review]
Still LGTM, thanks!
