### PR TITLE
fakecgo: C functions require nosplit

### LINKED ISSUE #287: `env CGO_ENABLED=0 go test "-gcflags=all=-N -l" -v ./...` causes SEGV
### PureGo Version

999f588e454888ff33d0f31b54c398940a961f53

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] Android
- [ ] iOS

### Go Version (`go version`)

go version go1.23.1 darwin/arm64

### What steps will reproduce the problem?

Run `env CGO_ENABLED=0 go test "-gcflags=all=-N -l" -v ./...`

### What is the expected result?

The tests pass

### What happens instead?

The tests causes SEGV.

```
% env CGO_ENABLED=0 go test "-gcflags=all=-N -l" -v ./...
?       github.com/ebitengine/purego/examples/libc      [no test files]
?       github.com/ebitengine/purego/examples/objc      [no test files]
?       github.com/ebitengine/purego/examples/window    [no test files]
?       github.com/ebitengine/purego/internal/cgo       [no test files]
?       github.com/ebitengine/purego/internal/fakecgo   [no test files]
?       github.com/ebitengine/purego/internal/load      [no test files]
?       github.com/ebitengine/purego/internal/strings   [no test files]
signal: segmentation fault
FAIL    github.com/ebitengine/purego    0.323s
signal: segmentation fault
FAIL    github.com/ebitengine/purego/objc       0.178s
FAIL
```

### Anything else you feel useful to add?

_No response_

### PR DESCRIPTION
**Pull request by TotallyGamerJet**
fakecgo runs on the system stack so we shouldn't ever split the stack.

I also updated the size of sigset_t to be the correct size based on the headers. This was needed to make it possible to build with inlining disabled when nosplit was added.

Fixes #287

### CODE REVIEW

File: internal/fakecgo/libcgo.go [hunk 1]
```diff
@@ -6,8 +6,11 @@
 package fakecgo
 
 type (
-	size_t         uintptr
-	sigset_t       [128]byte
+	size_t uintptr
+	// Sources:
+	// Darwin - https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/sys/_types.h#L74
+	// FreeBSD - https://github.com/DoctorWkt/xv6-freebsd/blob/d2a294c2a984baed27676068b15ed9a29b06ab6f/include/signal.h#L98C9-L98C21
+	sigset_t       [32]byte
```
Comment (hajimehoshi) [inline internal/fakecgo/libcgo.go:13]: What about Linux?

Comment (TotallyGamerJet) [reply internal/fakecgo/libcgo.go:13]: Ahh it is 128 bytes. Not sure what to do since if it's 128 then it's too big to build when inlining is disabled. I guess inline the functions by hand but that's kind of ugly.

https://github.com/torvalds/linux/blob/ab75170520d4964f3acf8bb1f91d34cbc650688e/arch/x86/include/asm/signal.h#L25

```
github.com/ebitengine/purego/internal/fakecgo.x_cgo_thread_start: nosplit stack over 792 byte limit
github.com/ebitengine/purego/internal/fakecgo.x_cgo_thread_start<1>
    grows 160 bytes, calls github.com/ebitengine/purego/internal/fakecgo._cgo_sys_thread_start<1>
        grows 400 bytes, calls github.com/ebitengine/purego/internal/fakecgo._cgo_try_pthread_create<1>
            grows 112 bytes, calls github.com/ebitengine/purego/internal/fakecgo.pthread_create<1>
                grows 128 bytes, calls github.com/ebitengine/purego/internal/fakecgo.call5<0>
                    grows 16 bytes, calls indirect
                        grows 0 bytes, calls runtime.morestack<0>
                        24 bytes over limit
            grows 112 bytes, calls github.com/ebitengine/purego/internal/fakecgo.nanosleep<1>
                grows 112 bytes, calls github.com/ebitengine/purego/internal/fakecgo.call5<0>
                    grows 16 bytes, calls indirect
                        grows 0 bytes, calls runtime.morestack<0>
                        8 bytes over limit
```

**Review by hajimehoshi — APPROVED** [review]
LGTM

File: internal/fakecgo/go_libinit.go [hunk 2]
```diff
@@ -50,17 +50,17 @@ func _cgo_try_pthread_create(thread *pthread_t, attr *pthread_attr_t, pfn unsafe
 	var err int
 
 	for tries = 0; tries < 20; tries++ {
-		err = int(pthread_create(thread, attr, pfn, unsafe.Pointer(arg)))
+		err = int(call5(pthread_createABI0, uintptr(unsafe.Pointer(thread)), uintptr(unsafe.Pointer(attr)), uintptr(pfn), uintptr(unsafe.Pointer(arg)), 0))
```
Comment (hajimehoshi) [inline internal/fakecgo/go_libinit.go:53]: It'd be nice if we leave comments why we use `call5`.

**Review by hajimehoshi — APPROVED** [review]
Still LGTM
